cobravsviper:
  log-level: "debug"
  
  rootflag1: "value from YAML configuration file root 1"
  rootflag2: "value from YAML configuration file root 2"
  rootflag3: "value from YAML configuration file root 3"
  #rootflag4: "value from YAML configuration file root 4" # we comment this to test if the viper takes the default value
  
  rootpersistentflag1: "value from YAML configuration file root 1"
  rootpersistentflag2: "value from YAML configuration file root 2"
  rootpersistentflag3: "value from YAML configuration file root 3"
  #rootpersistentflag4: "value from YAML configuration file root 4" # we comment this to test if the viper takes the default value
  
  # subcommand level 1
  grp2cmd2:
    grp2cmd2flag1: "value from YAML configuration file grp2cmd2 1"
    grp2cmd2flag2: "value from YAML configuration file grp2cmd2 2"
    grp2cmd2flag3: "value from YAML configuration file grp2cmd2 3"
    #grp2cmd2flag4: "value from YAML configuration file grp2cmd2 4" # we comment this to test if the viper takes the default value
    grp2cmd2persistentflag1: "value from YAML configuration file grp2cmd2 1"
    grp2cmd2persistentflag2: "value from YAML configuration file grp2cmd2 2"
    grp2cmd2persistentflag3: "value from YAML configuration file grp2cmd2 3"
    #grp2cmd2persistentflag4: "value from YAML configuration file grp2cmd2 4" # we comment this to test if the viper takes the default value
    
    # subcommand level 2
    sub221:
      sub221flag1: "value from YAML configuration file sub221 1"
      sub221flag2: "value from YAML configuration file sub221 2"
      sub221flag3: "value from YAML configuration file sub221 3"
      #sub221flag4: "value from YAML configuration file sub221 4" # we comment this to test if the viper takes the default value
  value from 
    zu-lu-sub221:
      zu-lu-sub221flag1: "value from YAML configuration file zu-lu-sub221 1"
      zu-lu-sub221flag2: "value from YAML configuration file zu-lu-sub221 2"
      zu-lu-sub221flag3: "value from YAML configuration file zu-lu-sub221 3"
      #zu-lu-sub221flag4: "value from YAML configuration file zu-lu-sub221 4" # we comment this to test if the viper takes the default value
  
  version:
    # Format of the version output. One of 'yaml' or 'json'.
    output: "json"
    pretty: true # only for JSON output